### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'MessagePort': An object could not be cloned.

### ISSUE THREAD

**Issue by paulyoder** [offirgolan/ember-burger-menu#16] opened 2016-12-25 19:24 UTC
I'm receiving this error when I installed the addon.

```
Uncaught DOMException: Failed to execute 'postMessage' on 'MessagePort': An object could not be cloned.
```

Any ideas what is causing this?

**Comment by offirgolan** [comment] 2016-12-26 00:23
@paulyoder I've never seen this issue before. Can you give me some more details here?

- Ember version
- Ember Burger Menu version
- A snippet of your template code

**Comment by christophersansone** [comment] 2017-01-09 17:12
I'm seeing this and can offer a bit more context.  For me, it occurs specifically when I am running Ember Inspector and have "Components" checked in the View Tree tab.  Toggling the "Components" checkbox from unchecked to checked will cause the error to occur every time for me.

I can reproduce it with a minimal template:

```javascript
{{#burger-menu as |burger|}}
  {{#burger.menu as |menu|}}
    {{#menu.item}}test{{/menu.item}}
  {{/burger.menu}}
  {{#burger.outlet}}
    {{outlet}}
  {{/burger.outlet}}
{{/burger-menu}}
```

Removing the `menu.item` component will cause it to not fail, so it seems that this is the culprit.

Running v0.2.0 of `ember-burger-menu`.

Interestingly I cannot reproduce it on the addon's live demo page.  Hmm.

Possibly related to https://github.com/emberjs/ember-inspector/issues/366 ?

**Comment by offirgolan** [comment] 2017-01-09 21:52
Hmmm okay I will take a look into this more now. @paulyoder thanks for providing some context on this. 

Do you have Ember prototype extensions disabled in your app?

**Comment by offirgolan** [comment] 2017-01-09 21:54
@christophersansone can you upgrade to the latest version of this addon and see if you are still getting this issue?

**Comment by offirgolan** [comment] 2017-01-27 21:34
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Closed by offirgolan** 2017-01-27 21:34 UTC
